import AnimatedText from "../components/AnimatedText";

export default function AnimatedName() {
  return (
    <>
      <div>
        <AnimatedText
          text="J"
          duration="10"
          delay="2"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="A"
          duration="11"
          delay="2.2"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="C"
          duration="9"
          delay="2.5"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="K"
          duration="11"
          delay="2.6"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="_"
          duration="11"
          delay="2.6"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="K"
          duration="15"
          delay="2"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="A"
          duration="10"
          delay="2.3"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="Z"
          duration="16"
          delay="2.9"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="A"
          duration="8"
          delay="2.7"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="N"
          duration="14"
          delay="2.5"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="J"
          duration="11"
          delay="2.6"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="Y"
          duration="13"
          delay="2.5"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="A"
          duration="16"
          delay="2"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
        <AnimatedText
          text="N"
          duration="11"
          delay="2.2"
          color1="white"
          color2="grey"
          fontSize="35"
          fontWeight="500"
        />
      </div>
      <style jsx>{`
        div {
          display: flex;
          flex-directopm: row;
          justify-content: center;
          margin: 35px;
        }
      `}</style>
    </>
  );
}
